// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/sba-guarantee-fee.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/sba-math.ts
var SBA_GUARANTEE_FEE_TIERS = [
  { upTo: 15e4, rate: 0.02 },
  { upTo: 7e5, rate: 0.03 },
  { upTo: 1e6, rate: 0.035 },
  { upTo: Infinity, rate: 0.035, rateOver: 0.0375, upToCap: 1e6 }
];
function calculateSBAGuaranteeFee(loanAmount, guaranteePercent) {
  if (!Number.isFinite(loanAmount) || loanAmount <= 0) return 0;
  const guaranteed = loanAmount * (guaranteePercent / 100);
  const tier = SBA_GUARANTEE_FEE_TIERS.find((t) => loanAmount <= t.upTo) ?? SBA_GUARANTEE_FEE_TIERS[SBA_GUARANTEE_FEE_TIERS.length - 1];
  if (tier.rateOver !== void 0 && tier.upToCap !== void 0) {
    const under = Math.min(guaranteed, tier.upToCap);
    const over = Math.max(0, guaranteed - tier.upToCap);
    return under * tier.rate + over * tier.rateOver;
  }
  return guaranteed * tier.rate;
}
function computeNewLoanAnnualPayment(principal, interestRatePct, termMonths) {
  if (!Number.isFinite(interestRatePct) || interestRatePct <= 0) return 0;
  if (!Number.isFinite(termMonths) || termMonths <= 0) return 0;
  if (!Number.isFinite(principal) || principal <= 0) return 0;
  const r = interestRatePct / 100 / 12;
  const monthly = principal * (r * Math.pow(1 + r, termMonths)) / (Math.pow(1 + r, termMonths) - 1);
  return monthly * 12;
}
function computeSBALoanAmount(primaryRequest, equityInjection, guaranteePercent, financeFee) {
  const gp = Number.isFinite(guaranteePercent) ? guaranteePercent : 75;
  const equity = Number.isFinite(equityInjection) ? equityInjection : 0;
  if (!financeFee) return Math.max(0, primaryRequest - equity);
  let sba = Math.max(0, primaryRequest - equity);
  for (let i = 0; i < 12; i++) {
    const fee = calculateSBAGuaranteeFee(sba, gp);
    const newSba = Math.max(0, primaryRequest + fee - equity);
    if (Math.abs(newSba - sba) < 1) {
      sba = newSba;
      break;
    }
    sba = newSba;
  }
  return sba;
}
function computeDownPaymentAndLoan(primaryRequest, downPaymentPct, guaranteePercent, financeFee) {
  const gp = Number.isFinite(guaranteePercent) ? guaranteePercent : 75;
  const pct = Math.max(0, Math.min(100, downPaymentPct || 0)) / 100;
  if (primaryRequest <= 0) return { equity: 0, loan: 0, fee: 0, totalProject: 0 };
  let equity = pct * primaryRequest;
  let loan = 0;
  let fee = 0;
  for (let i = 0; i < 20; i++) {
    loan = financeFee ? Math.max(0, primaryRequest + fee - equity) : Math.max(0, primaryRequest - equity);
    const newFee = calculateSBAGuaranteeFee(loan, gp);
    const totalProject = primaryRequest + newFee;
    const newEquity = pct * totalProject;
    if (Math.abs(newFee - fee) < 0.5 && Math.abs(newEquity - equity) < 0.5) {
      fee = newFee;
      equity = newEquity;
      loan = financeFee ? Math.max(0, primaryRequest + fee - equity) : Math.max(0, primaryRequest - equity);
      break;
    }
    fee = newFee;
    equity = newEquity;
  }
  return { equity: Math.round(equity), loan, fee, totalProject: primaryRequest + fee };
}
function computeSBAAnnualServiceFee(sbaLoanAmount, guaranteePercent) {
  if (!Number.isFinite(sbaLoanAmount) || sbaLoanAmount <= 0) return 0;
  const gp = Number.isFinite(guaranteePercent) ? guaranteePercent : 75;
  return sbaLoanAmount * (gp / 100) * 55e-4;
}

// src/lib/mcp/tools/sba-guarantee-fee.ts
var sba_guarantee_fee_default = defineTool({
  name: "sba_guarantee_fee",
  title: "SBA 7(a) upfront guarantee fee",
  description: "Calculate the SBA 7(a) upfront guarantee fee for a given loan amount and guarantee percentage using the FY2026 tier table.",
  inputSchema: {
    loanAmount: z.number().positive().describe("Total SBA 7(a) loan amount in USD."),
    guaranteePercent: z.number().min(0).max(100).describe("SBA guarantee percentage (e.g. 75 or 85).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ loanAmount, guaranteePercent }) => {
    const fee = calculateSBAGuaranteeFee(loanAmount, guaranteePercent);
    const guaranteed = loanAmount * (guaranteePercent / 100);
    return {
      content: [
        {
          type: "text",
          text: `SBA upfront guarantee fee: $${fee.toFixed(2)} (guaranteed portion: $${guaranteed.toFixed(2)})`
        }
      ],
      structuredContent: { fee, guaranteedPortion: guaranteed, loanAmount, guaranteePercent }
    };
  }
});

// src/lib/mcp/tools/sba-loan-sizing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var sba_loan_sizing_default = defineTool2({
  name: "sba_loan_sizing",
  title: "SBA 7(a) loan sizing (Sources & Uses plug)",
  description: "Given the total primary financing request (uses), an equity injection, guarantee %, and whether the upfront fee is financed, solve for the SBA 7(a) loan amount, upfront fee, annual P&I, and annual SBA service fee. Mirrors the Summary tab's Sources & Uses solver.",
  inputSchema: {
    primaryRequest: z2.number().positive().describe("Sum of Uses of Funds excluding SBA guarantee fee (USD)."),
    equityInjection: z2.number().min(0).describe("Borrower equity injection (USD)."),
    guaranteePercent: z2.number().min(0).max(100).describe("SBA guarantee percent (e.g. 75)."),
    financeFee: z2.boolean().describe("If true, the SBA upfront fee is rolled into the loan (circular). If false, treat fee as a separate borrower injection source."),
    interestRatePct: z2.number().positive().optional().describe("Optional: annual interest % for P&I."),
    termMonths: z2.number().positive().optional().describe("Optional: amortization term in months for P&I.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ primaryRequest, equityInjection, guaranteePercent, financeFee, interestRatePct, termMonths }) => {
    const loan = computeSBALoanAmount(primaryRequest, equityInjection, guaranteePercent, financeFee);
    const upfrontFee = calculateSBAGuaranteeFee(loan, guaranteePercent);
    const annualServiceFee = computeSBAAnnualServiceFee(loan, guaranteePercent);
    const annualPI = interestRatePct && termMonths ? computeNewLoanAnnualPayment(loan, interestRatePct, termMonths) : void 0;
    const totalProject = primaryRequest + upfrontFee;
    const lines = [
      `SBA 7(a) loan amount: $${loan.toFixed(2)}`,
      `Upfront guarantee fee: $${upfrontFee.toFixed(2)} (${financeFee ? "financed into loan" : "borrower-injected"})`,
      `Annual SBA service fee (0.55% on guaranteed portion): $${annualServiceFee.toFixed(2)}`,
      `Total project cost: $${totalProject.toFixed(2)}`
    ];
    if (annualPI !== void 0) {
      lines.push(`Annual P&I: $${annualPI.toFixed(2)} (monthly $${(annualPI / 12).toFixed(2)})`);
    }
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: {
        sbaLoanAmount: loan,
        upfrontGuaranteeFee: upfrontFee,
        annualServiceFee,
        annualPrincipalAndInterest: annualPI,
        totalProjectCost: totalProject,
        inputs: { primaryRequest, equityInjection, guaranteePercent, financeFee, interestRatePct, termMonths }
      }
    };
  }
});

// src/lib/mcp/tools/loan-payment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var loan_payment_default = defineTool3({
  name: "loan_payment",
  title: "Amortizing loan payment",
  description: "Compute the monthly and annual principal & interest payment for a fully-amortizing loan.",
  inputSchema: {
    principal: z3.number().positive().describe("Loan principal in USD."),
    interestRatePct: z3.number().positive().describe("Annual interest rate as a percent, e.g. 9.5"),
    termMonths: z3.number().positive().describe("Amortization term in months, e.g. 120")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ principal, interestRatePct, termMonths }) => {
    const annual = computeNewLoanAnnualPayment(principal, interestRatePct, termMonths);
    const monthly = annual / 12;
    return {
      content: [
        {
          type: "text",
          text: `Monthly P&I: $${monthly.toFixed(2)} \u2014 Annual debt service: $${annual.toFixed(2)}`
        }
      ],
      structuredContent: { monthlyPayment: monthly, annualDebtService: annual, principal, interestRatePct, termMonths }
    };
  }
});

// src/lib/mcp/tools/down-payment-solver.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var down_payment_solver_default = defineTool4({
  name: "down_payment_solver",
  title: "Down payment on total project cost",
  description: "Solve iteratively for the equity injection and resulting SBA 7(a) loan when the down payment is a percentage of total project cost (primary request + upfront fee).",
  inputSchema: {
    primaryRequest: z4.number().positive().describe("Sum of Uses of Funds excluding fee (USD)."),
    downPaymentPct: z4.number().min(0).max(100).describe("Down payment as % of total project cost."),
    guaranteePercent: z4.number().min(0).max(100).describe("SBA guarantee percent (e.g. 75)."),
    financeFee: z4.boolean().describe("Whether the upfront SBA fee is financed into the loan.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ primaryRequest, downPaymentPct, guaranteePercent, financeFee }) => {
    const r = computeDownPaymentAndLoan(primaryRequest, downPaymentPct, guaranteePercent, financeFee);
    const meets10 = r.totalProject > 0 && r.equity / r.totalProject >= 0.1;
    return {
      content: [
        {
          type: "text",
          text: [
            `Equity injection: $${r.equity.toFixed(2)}`,
            `SBA loan: $${r.loan.toFixed(2)}`,
            `Upfront fee: $${r.fee.toFixed(2)}`,
            `Total project cost: $${r.totalProject.toFixed(2)}`,
            `Meets 10% minimum: ${meets10 ? "yes" : "no"}`
          ].join("\n")
        }
      ],
      structuredContent: { ...r, meetsTenPercentMinimum: meets10 }
    };
  }
});

// src/lib/mcp/tools/dscr.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var dscr_default = defineTool5({
  name: "dscr",
  title: "Debt Service Coverage Ratio",
  description: "Compute DSCR = cash flow available for debt service / total annual debt service. Optionally annualizes interim cash flow by period months.",
  inputSchema: {
    cashFlow: z5.number().describe("Cash flow available for debt service for the period (USD). Business CFADS, global net cash, etc."),
    annualDebtService: z5.number().positive().describe("Total annual debt service (USD)."),
    periodMonths: z5.number().positive().max(24).optional().describe("If the cash flow is for a partial period, months in that period. Cash flow will be annualized as cashFlow \xD7 12 / periodMonths.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ cashFlow, annualDebtService, periodMonths }) => {
    const annualized = periodMonths && periodMonths > 0 && periodMonths < 12 ? cashFlow * 12 / periodMonths : cashFlow;
    const dscr = annualDebtService > 0 ? annualized / annualDebtService : 0;
    const flag = dscr >= 1.25 ? "meets 1.25x SBA benchmark" : dscr >= 1 ? "covers but below 1.25x" : "does NOT cover debt service";
    return {
      content: [
        {
          type: "text",
          text: `DSCR: ${dscr.toFixed(2)}x \u2014 ${flag}. (Annualized CFADS $${annualized.toFixed(2)} / Annual DS $${annualDebtService.toFixed(2)})`
        }
      ],
      structuredContent: { dscr, annualizedCashFlow: annualized, annualDebtService, periodMonths: periodMonths ?? 12 }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sba-spreading-tool-mcp",
  title: "SBA Spreading Tool \u2014 Calculators",
  version: "0.1.0",
  instructions: "Public calculators from the SBA financial spreading tool. Stateless: no access to any user's saved spread. Use `sba_loan_sizing` for the Sources & Uses plug, `sba_guarantee_fee` for the FY2026 upfront fee tiers, `loan_payment` for amortizing P&I, `down_payment_solver` for a % of total-project-cost down payment, and `dscr` for coverage ratios (with optional interim annualization).",
  tools: [sba_loan_sizing_default, sba_guarantee_fee_default, loan_payment_default, down_payment_solver_default, dscr_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
